services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:28.1
    command: "-fallbackfee=0.0002"
    environment:
      MYUID: 1000
      MYGID: 1000
      RPCAUTH: "user:84c66d54d736d8b02aaa5b02e07e759b$$cc56c229b2a49ae2bfd5932cc8a6135d435bb9a7ac037ddd351d65936082c03d"
    ports:
      - 18443:18443
      - 18444:18444
    volumes:
      - ./datacore:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.10.9
    environment:
      MYUID: 1000
      MYGID: 1000
      BTCHOST: "192.168.1.9"
      BTCRPCPORT: "18443"
      BTCP2PPORT: "18444"
      BTCUSER: "user"
      BTCPASS: "password"
      NETWORK: "regtest"
      LOG_LEVEL: "info"
      PORT: "50001"
      MONITORING_PORT: "24224"
    volumes:
      - ./dataindex:/srv/app/db
    depends_on:
      - bitcoind
    ports:
      - 50001:50001
  proxy:
    image: ghcr.io/rgb-tools/rgb-proxy-server:0.3.0
    ports:
      - 3000:3000
