name: Build

on:
  push:
    branches: [ "feature_lnfi_build" ]
  pull_request:
    branches: [ "feature_lnfi_build" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable ]
        name: [ linux, windows, macos ]
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
          - name: macos
            os: macos-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
      - name: Build
        run: cargo build --release --features c_bindings
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rgb-lightning-node-${{ matrix.name }}-${{ matrix.toolchain }}
          path: target/${{ matrix.os == 'windows' && 'release/rgb-lightning-node.exe' || 'release/rgb-lightning-node' }}